import {beforeEach,afterEach,describe,it,expect,vi} from "vitest";
const wallet="0x1111111111111111111111111111111111111111",target="0x2222222222222222222222222222222222222222",quote="0xeCe5cA8bf9220718E5727754026757512212cb3c",usdc="0x3600000000000000000000000000000000000000";
const m=vi.hoisted(()=>({market:vi.fn(),estimate:vi.fn(),sell:vi.fn(),balance:vi.fn(),held:vi.fn(),block:vi.fn()}));
vi.mock("../lib/arc/markets",()=>({tradeMarket:m.market,marketScope:()=>"arc-mainnet"}));
vi.mock("../lib/arc/config",()=>({arcConfigFromEnv:()=>({})}));
vi.mock("../lib/arc/rpc",()=>({createArcRpc:()=>({tokenBalance:m.held,block:m.block}),checkArcRpc:async()=>({number:1n,hash:"same"})}));
vi.mock("../lib/arc/trading",()=>({estimateArcReferenceTrade:m.estimate,arcSellAmountForUsdc:m.sell}));
vi.mock("../lib/arc/wallet-tokens",()=>({arcSelectedTokenBalance:m.balance}));
import {resolveTradePlan,chooseBuyFunding,type TradeRequest} from "../lib/arc/trade-plan";
const buy:TradeRequest={side:"buy",token:target,amount:"20",unit:"usd",slippageBps:100};
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv("WEB_AUTH_SECRET","plan-secret");m.market.mockResolvedValue({token:target,paired:true,quote:{address:quote,symbol:"ARGUS",decimals:18}});m.held.mockResolvedValue(500n*10n**18n);m.block.mockResolvedValue({hash:"same"});m.estimate.mockResolvedValue({amountOut:"100"});m.sell.mockResolvedValue("2000");m.balance.mockResolvedValue({maxSellRaw:"1000000000000000000000",decimals:18});});
afterEach(()=>{vi.unstubAllEnvs();vi.useRealTimers();});
describe("paired funding plans",()=>{
 it('buys and sells through a newly discovered non-ARGUS pair',async()=>{
   const arcash='0x0bffa97f774824e9da843699aedd2835cb1b8022';
   m.market.mockResolvedValue({token:target,paired:true,quote:{address:arcash,symbol:'ARCASH',decimals:8}});
   m.held.mockResolvedValue(200n*10n**8n);
   const held=await resolveTradePlan(wallet,buy);expect(held.trade).toMatchObject({tokenIn:arcash,amount:'100'});expect(held.funding.inputSymbol).toBe('ARCASH');
   m.held.mockResolvedValue(0n);const funded=await resolveTradePlan(wallet,buy);expect(funded.trade.tokenIn).toBe('native');expect(funded.funding.quoteSymbol).toBe('ARCASH');
   const sell=await resolveTradePlan(wallet,{...buy,side:'sell',unit:'tokens',amount:'12'});expect(sell.trade.tokenOut).toBe(arcash);expect(sell.funding.outputSymbol).toBe('ARCASH');
 });
 it("uses held ARGUS and returns the exact spending asset for display",async()=>{const p=await resolveTradePlan(wallet,buy);expect(p.trade).toMatchObject({tokenIn:quote,tokenOut:target,amount:"100"});expect(p.funding).toMatchObject({inputSymbol:"ARGUS",inputAmount:"100",mode:"quote"});});
 it("uses USDC for the entire buy when ARGUS is insufficient",async()=>{m.held.mockResolvedValue(99n*10n**18n);const p=await resolveTradePlan(wallet,buy);expect(p.trade).toMatchObject({tokenIn:"native",amount:"20",tokenOut:target});expect(p.funding.mode).toBe("usdc");});
 it("skips the conversion lookup when no ARGUS is held",async()=>{m.held.mockResolvedValue(0n);expect((await resolveTradePlan(wallet,buy)).funding.inputSymbol).toBe("USDC");expect(m.estimate).not.toHaveBeenCalled();});
 it("honors explicit USDC even when ARGUS is held",async()=>{expect((await resolveTradePlan(wallet,{...buy,funding:"usdc"})).trade.tokenIn).toBe("native");expect(m.held).not.toHaveBeenCalled();});
 it("keeps an explicit ARGUS amount in token units",async()=>{const p=await resolveTradePlan(wallet,{...buy,unit:"quote",expectedQuote:quote,amount:"1.5"});expect(p.trade.amount).toBe("1.5");expect(m.estimate).not.toHaveBeenCalled();});
 it("does not silently change an explicit ARGUS buy to USDC",async()=>{m.held.mockResolvedValue(0n);await expect(resolveTradePlan(wallet,{...buy,unit:"quote",amount:"10"})).rejects.toThrow("Not enough");});
 it("rejects the wrong quote token",async()=>{await expect(resolveTradePlan(wallet,{...buy,unit:"quote",expectedQuote:target})).rejects.toThrow("different quote");});
 it("sells directly to ARGUS",async()=>{const p=await resolveTradePlan(wallet,{...buy,side:"sell",unit:"tokens",amount:"123.45"});expect(p.trade).toMatchObject({tokenIn:target,tokenOut:quote,amount:"123.45"});expect(p.funding.outputSymbol).toBe("ARGUS");});
 it("values a dollar sell without changing its ARGUS receive asset",async()=>{const p=await resolveTradePlan(wallet,{...buy,side:"sell"});expect(m.sell).toHaveBeenCalledWith(wallet,target,"20");expect(p.trade).toMatchObject({tokenOut:quote,amount:"2000"});});
 it("uses the tax-aware percentage amount",async()=>{const p=await resolveTradePlan(wallet,{...buy,side:"sell",unit:"percent",amount:"25"});expect(p.trade).toMatchObject({amount:"250",tokenOut:quote});});
 it("does not change ordinary USDC markets",async()=>{m.market.mockResolvedValue({token:target,paired:false,quote:{address:usdc,symbol:"USDC",decimals:6}});expect((await resolveTradePlan(wallet,buy)).trade).toMatchObject({tokenIn:"native",amount:"20"});expect((await resolveTradePlan(wallet,{...buy,side:"sell",unit:"tokens"})).trade.tokenOut).toBe("native");expect(m.held).not.toHaveBeenCalled();});
 it("preserves funding and input amount across approval recovery without rediscovery",async()=>{const p=await resolveTradePlan(wallet,buy,{context:"x:123"});m.held.mockResolvedValue(0n);m.estimate.mockResolvedValue({amountOut:"200"});m.market.mockClear();const resumed=await resolveTradePlan(wallet,buy,{context:"x:123",fundingPlan:p.fundingPlan,routeHint:"new-route"});expect(resumed.trade).toMatchObject({tokenIn:quote,amount:"100",routeHint:"new-route"});expect(resumed.fundingPlan).toBe(p.fundingPlan);expect(m.market).not.toHaveBeenCalled();});
 it.each([{amount:"21"},{token:usdc},{side:"sell" as const},{unit:"quote" as const},{slippageBps:200},{funding:"usdc" as const}])("binds a plan to the displayed request: %j",async change=>{const p=await resolveTradePlan(wallet,buy);await expect(resolveTradePlan(wallet,{...buy,...change},{fundingPlan:p.fundingPlan})).rejects.toThrow("funding changed");});
 it("binds the wallet, channel and request id",async()=>{const p=await resolveTradePlan(wallet,buy,{context:"x:1"});await expect(resolveTradePlan(target,buy,{context:"x:1",fundingPlan:p.fundingPlan})).rejects.toThrow();await expect(resolveTradePlan(wallet,buy,{context:"x:2",fundingPlan:p.fundingPlan})).rejects.toThrow();await expect(resolveTradePlan(wallet,buy,{fundingPlan:p.fundingPlan})).rejects.toThrow();});
 it("rejects tampering and expired plans instead of silently selecting another asset",async()=>{vi.useFakeTimers();const p=await resolveTradePlan(wallet,buy);const [payload,sig]=p.fundingPlan.split('.');await expect(resolveTradePlan(wallet,buy,{fundingPlan:payload+'A.'+sig})).rejects.toThrow();vi.advanceTimersByTime(30*60_000+1);await expect(resolveTradePlan(wallet,buy,{fundingPlan:p.fundingPlan})).rejects.toThrow("expired");});
 it("does not decide funding from an unavailable balance",async()=>{m.held.mockRejectedValue(Error("RPC unavailable"));await expect(resolveTradePlan(wallet,buy)).rejects.toThrow("RPC unavailable");});
 it("accepts an exact sufficient balance and rejects partial explicit funding",()=>{expect(chooseBuyFunding(true,"auto",100n,100n)).toBe("quote");expect(chooseBuyFunding(true,"auto",99n,100n)).toBe("usdc");expect(()=>chooseBuyFunding(true,"quote",99n,100n)).toThrow();});
});
