import {beforeEach, expect, it, vi} from "vitest";
import {SocialTokenResolutionError} from "../lib/arc/social-token-resolution";
const m=vi.hoisted(()=>({enabled:true,read:vi.fn(),command:vi.fn(),resolve:vi.fn(),report:vi.fn(),run:vi.fn(),funding:vi.fn()}));
vi.mock("../lib/fee-report/policy",async original=>({...await original<typeof import("../lib/fee-report/policy")>(),get FEE_SOCIAL_ENABLED(){return m.enabled;}}));
vi.mock("../lib/otc/repository",()=>({repository:()=>({read:m.read,command:m.command})}));
vi.mock("../lib/arc/indexed-social-token",()=>({indexedSocialToken:m.resolve}));
vi.mock("../lib/fee-report/read",()=>({readFeeReport:m.report}));
vi.mock("../lib/fee-report/history-service",()=>({readServiceFeeReport:m.report}));
vi.mock("../lib/fee-report/execution",()=>({runFeeJob:m.run}));
vi.mock("../lib/fee-report/funding",()=>({feeFunding:m.funding}));
import {socialFees} from "../lib/fee-report/social";
import {emptyReport,feeReportInput} from "../lib/fee-report/model";
import {groundedCanonicalCommand} from "../convex/xWalletIntent";
const token=`0x${"11".repeat(20)}`,auth=()=>({owner:"user:123",source:"x",createdAt:Date.now()});
beforeEach(()=>{vi.clearAllMocks();m.enabled=true;m.read.mockResolvedValue(null);m.command.mockResolvedValue(true);m.resolve.mockResolvedValue(token);m.report.mockResolvedValue({...emptyReport(feeReportInput.parse({token})),status:"partial"});m.run.mockResolvedValue({ok:true,pending:false,message:"Complete"});m.funding.mockResolvedValue("100");});
it("keeps new social requests disabled without token reads or admission",async()=>{m.enabled=false;expect(await socialFees(auth(),"1",{kind:"claim_fees",token:"ARGOS"})).toMatchObject({ok:false});expect(m.command).not.toHaveBeenCalled();expect(m.resolve).not.toHaveBeenCalled();expect(m.run).not.toHaveBeenCalled();});
it("recovers saved claims even while release is disabled",async()=>{m.enabled=false;m.read.mockResolvedValue({id:"saved"});expect(await socialFees(auth(),"1",{kind:"claim_fees",token:"ARGOS"})).toMatchObject({ok:true});expect(m.run).toHaveBeenCalledTimes(1);expect(m.command).not.toHaveBeenCalled();});
it("checks without admitting or executing any workflow",async()=>{expect(await socialFees(auth(),"1",{kind:"check_fees",token:"ARGOS"})).toMatchObject({ok:true});expect(m.command.mock.calls.map(c=>c[0])).toEqual(["fee_report_limit"]);expect(m.run).not.toHaveBeenCalled();expect(m.funding).not.toHaveBeenCalled();});
it("reports ambiguous ticker input instead of false pending transactions",async()=>{m.resolve.mockRejectedValue(new SocialTokenResolutionError("More than one token uses ABC. Enter its contract address."));expect(await socialFees(auth(),"1",{kind:"check_fees",token:"ABC"})).toMatchObject({ok:false,message:expect.stringContaining("contract address")});expect(m.report).not.toHaveBeenCalled();});
it("applies rate limits before external lookups",async()=>{m.command.mockResolvedValue(false);expect(await socialFees(auth(),"1",{kind:"check_fees",token:"ARGOS"})).toMatchObject({ok:false,message:expect.stringContaining("rate limit")});expect(m.resolve).not.toHaveBeenCalled();});
it("admits a free claim using authenticated identity before execution",async()=>{await socialFees({...auth(),source:"telegram"},"1",{kind:"claim_fees",token:"ARGOS"});expect(m.command).toHaveBeenCalledWith("fee_admit",expect.objectContaining({principal:"user:123",channel:"telegram",token,sourceRequestId:"1"}));expect(m.run).toHaveBeenCalledTimes(1);});
it.each(["check fees for ARGOS","show me creator fees on ARGOS","@TheArgosBot could you please get fees for $ARGOS?"])("grounds read-only X fee commands: %s",text=>expect(groundedCanonicalCommand(text)).toEqual({kind:"check_fees",token:"ARGOS"}));
it.each(["claim fees for ARGOS","collect creator fees from ARGOS"])("grounds X claims: %s",text=>expect(groundedCanonicalCommand(text)).toEqual({kind:"claim_fees",token:"ARGOS"}));
