import {beforeEach,afterEach,it,expect,vi} from "vitest";
import {NextRequest} from "next/server";
const m=vi.hoisted(()=>({session:vi.fn(),query:vi.fn(),advance:vi.fn()}));
vi.mock("../lib/otc/http",async original=>({...await original<typeof import("../lib/otc/http")>(),websiteSession:m.session}));
vi.mock("convex/browser",()=>({ConvexHttpClient:class{query=m.query;}}));
vi.mock("../lib/launches/service",()=>({advanceLaunch:m.advance,launchBackend:()=>({read:m.query})}));
import {GET,POST} from "../app/api/wallet/launches/route";
import {WebError} from "../lib/otc/http";
const id="00000000-0000-4000-8000-000000000001",address="0x1111111111111111111111111111111111111111";
const post=(action:string)=>new NextRequest("https://www.argosbot.io/api/wallet/launches",{method:"POST",body:JSON.stringify({action,requestId:id,...(action==="execute"||action==="update"?{revision:1}:{}),...(action==="create"||action==="update"?{input:{}}:{})})});
beforeEach(()=>{vi.resetAllMocks();vi.stubEnv("NEXT_PUBLIC_CONVEX_URL","https://example.convex.cloud");vi.stubEnv("WEB_AUTH_SECRET","secret");m.session.mockResolvedValue({owner:"1",walletAddress:address});m.query.mockResolvedValue({requestId:id,status:"prepared"});});
afterEach(()=>vi.unstubAllEnvs());
it.each(["create","update","prepare","execute","cancel"])("blocks website %s before any execution",async action=>{const r=await POST(post(action));expect(r.status).toBe(403);expect(await r.json()).toMatchObject({acceptance:"rejected"});expect(m.advance).not.toHaveBeenCalled();});
it("keeps authenticated saved status readable while paused",async()=>{vi.stubEnv("ARGUS_LAUNCH_PREPARATION_ENABLED","false");expect((await GET(new NextRequest(`https://www.argosbot.io/api/wallet/launches?requestId=${id}`))).status).toBe(200);expect(m.query).toHaveBeenCalledWith(expect.anything(),expect.objectContaining({owner:"1",address}));});
it("recovers only the signed-in owner's existing launch",async()=>{m.advance.mockResolvedValue({status:"running"});expect((await POST(post("resume"))).status).toBe(200);expect(m.advance).toHaveBeenCalledWith("1",address,id);});
it("marks authentication rejection and never starts work",async()=>{m.session.mockRejectedValue(new WebError("Sign in again.",401));const r=await POST(post("execute"));expect(r.status).toBe(401);expect(await r.json()).toMatchObject({acceptance:"rejected"});expect(m.advance).not.toHaveBeenCalled();});
it("does not label a lost recovery response as an unaccepted launch",async()=>{m.advance.mockRejectedValue(Error("private-provider-secret"));const r=await POST(post("resume"));expect(r.status).toBe(503);const b=await r.json();expect(b).not.toHaveProperty("acceptance");expect(JSON.stringify(b)).not.toContain("private-provider-secret");});
