import {describe,it,expect} from 'vitest';
import {serializeTransaction,parseTransaction,type Hex} from 'viem';
import {prepareReplacement,selectMinedAttempt,reconcileMinedNonce} from '../lib/otc/signed-recovery';
import {beginSigning,cancelUnsignedTrade,staleUnsigned} from '../lib/otc/unsigned-recovery';
import {signTransactionRecord,settled} from '../lib/otc/transactions';
import {type Store,type RecordValue,type Transaction,type Wallet,walletId} from '../lib/otc/model';
const address='0x1111111111111111111111111111111111111111',to='0x2222222222222222222222222222222222222222';
const encoded=(fee=100n,recipient=to)=>serializeTransaction({type:'eip1559',chainId:5042,nonce:7,to:recipient as Hex,value:10n,gas:21000n,maxFeePerGas:fee,maxPriorityFeePerGas:fee/10n});
function fixture(){
 const rows=new Map<string,RecordValue>(),store:Store={get:async<T extends RecordValue>(id:string)=>structuredClone(rows.get(id)??null) as T|null,put:async r=>{rows.set(r.id,structuredClone(r));}};
 const tx:Transaction={kind:'transaction',id:'tx:test',owner:'owner',wallet:address,chainId:5042,leg:'send',holdId:'tx:test',status:'submitted',recoveryVersion:1,signingStartedAt:1,unsigned:encoded(),raw:'0x01',hash:'old',createdAt:1,updatedAt:1};
 const w:Wallet={kind:'wallet',id:walletId(5042,address),owner:'owner',address,chainId:5042,activeTx:tx.id,holds:{[tx.id]:'2100010',listing:'100'},updatedAt:1};rows.set(tx.id,tx);rows.set(w.id,w);
 const input={id:tx.id,expectedHash:'old',unsigned:encoded(120n),reserveWei:'2520010',balanceWei:'5000000',block:'10'};
 return {rows,store,tx,w,input};
}
describe('signed fee recovery',()=>{
 it('keeps the old bytes, nonce and every unrelated hold',async()=>{const f=fixture();const next=await prepareReplacement(f.store,f.input,2);expect(next.previousSigned).toEqual([{unsigned:f.tx.unsigned,raw:'0x01',hash:'old',revision:0}]);expect(next.signingRevision).toBe(1);expect(next.signingStartedAt).toBe(2);expect(next.raw).toBeUndefined();expect(parseTransaction(next.unsigned as Hex).nonce).toBe(7);expect(await f.store.get(f.w.id)).toMatchObject({activeTx:f.tx.id,holds:{[f.tx.id]:'2520010',listing:'100'}});await expect(cancelUnsignedTrade(f.store,f.tx.id,9999999,'owner')).rejects.toThrow('safely');});
 it.each(['recipient','nonce','gas','amount','fee','underfunded','stale-hash'])('rejects unsafe replacement: %s',async mode=>{const f=fixture();if(mode==='recipient')f.input.unsigned=encoded(120n,address);if(mode==='nonce'||mode==='gas'||mode==='amount'){const t=parseTransaction(f.input.unsigned as Hex);f.input.unsigned=serializeTransaction({type:'eip1559',chainId:5042,nonce:mode==='nonce'?8:7,to,value:mode==='amount'?11n:10n,gas:mode==='gas'?22000n:21000n,maxFeePerGas:t.maxFeePerGas,maxPriorityFeePerGas:t.maxPriorityFeePerGas});}if(mode==='fee')f.input.unsigned=encoded(101n);if(mode==='underfunded')f.input.balanceWei='2520010';if(mode==='stale-hash')f.input.expectedHash='other';await expect(prepareReplacement(f.store,f.input,2)).rejects.toThrow();expect(await f.store.get(f.w.id)).toEqual(f.w);});
 it('reconciles an original transaction winning before replacement signing completes',async()=>{const f=fixture();await prepareReplacement(f.store,f.input,2);const selected=await selectMinedAttempt(f.store,f.tx.id,'old',3);expect(selected).toMatchObject({unsigned:f.tx.unsigned,raw:f.tx.raw,hash:'old',status:'submitted'});await expect(signTransactionRecord(f.store,f.tx.id,'0x02','new',4,f.input.unsigned)).rejects.toThrow('changed');});
 it('rejects a late settlement of the wrong fee version',async()=>{const f=fixture();await prepareReplacement(f.store,f.input,2);await signTransactionRecord(f.store,f.tx.id,'0x02','new',3,f.input.unsigned);await expect(settled(f.store,f.tx.id,'10',true,4,undefined,'old')).rejects.toThrow('changed');expect((await f.store.get<Wallet>(f.w.id))!.activeTx).toBe(f.tx.id);});
 it('does not duplicate concurrent replacement preparation',async()=>{const f=fixture();await prepareReplacement(f.store,f.input,2);await expect(prepareReplacement(f.store,f.input,3)).rejects.toThrow();});
 it('adopts an independently mined matching call but still requires normal delivery checks',async()=>{const f=fixture();const next=await reconcileMinedNonce(f.store,{id:f.tx.id,expectedHash:'old',unsigned:encoded(120n),raw:'0x02',hash:'mined',block:'10'},2);expect(next.status).toBe('submitted');expect(next.hash).toBe('mined');expect((await f.store.get<Wallet>(f.w.id))!.activeTx).toBe(f.tx.id);});
 it('releases only the original standalone hold after proven conflicting nonce consumption',async()=>{const f=fixture();const next=await reconcileMinedNonce(f.store,{id:f.tx.id,expectedHash:'old',unsigned:encoded(120n,address),raw:'0x02',hash:'mined',block:'10'},2);expect(next.status).toBe('cancelled');expect(next.nonceConflict).toEqual({hash:'mined',block:'10'});expect((await f.store.get<Wallet>(f.w.id))!.holds).toEqual({listing:'100'});});
});
describe('unsigned send and approval recovery',()=>{
 it.each(['send','allowance'] as const)('expires unsigned %s after fifteen minutes',async leg=>{const f=fixture();Object.assign(f.tx,{leg,status:'prepared'});delete f.tx.raw;delete f.tx.hash;delete f.tx.signingStartedAt;expect(staleUnsigned(f.tx,900001)).toBe(true);expect(staleUnsigned(f.tx,899999)).toBe(false);await cancelUnsignedTrade(f.store,f.tx.id,900001);expect((await f.store.get<Wallet>(f.w.id))!.holds).toEqual({listing:'100'});await expect(beginSigning(f.store,f.tx.id,900002)).rejects.toThrow();});
 it('permits an owner cancellation before timeout, but never after signing starts',async()=>{const f=fixture();Object.assign(f.tx,{status:'prepared'});delete f.tx.raw;delete f.tx.hash;delete f.tx.signingStartedAt;await expect(cancelUnsignedTrade(f.store,f.tx.id,2,'other')).rejects.toThrow('owner');await beginSigning(f.store,f.tx.id,2);await expect(cancelUnsignedTrade(f.store,f.tx.id,3,'owner')).rejects.toThrow('safely');});
});
