"use client";
import { useEffect, useRef, useState } from "react";
import { useWalletSession } from "./WalletSessionProvider";
import { WalletSignInButton } from "./WalletSignInButton";
import type { rewardSnapshot } from "@/lib/launches/reward-service";
type Snapshot=Awaited<ReturnType<typeof rewardSnapshot>>;
type Request={token:string;requestId:string;action:"distribute"|"holders";offset:number};
const amount=(value:string)=>Number(value).toLocaleString(undefined,{maximumFractionDigits: Number(value)>0&&Number(value)<.01?6:2});
export function ClaimControls(){
  const session=useWalletSession(),[token,setToken]=useState(""),[data,setData]=useState<Snapshot|null>(null),[loading,setLoading]=useState(false),[notice,setNotice]=useState(""),[hash,setHash]=useState<string>(),[job,setJob]=useState<Request|null>(null),[busy,setBusy]=useState(false),[offset,setOffset]=useState(0);
  const running=useRef(false),epoch=useRef(0);
  const key=session?.walletAddress?`argos-claim:${session.walletAddress.toLowerCase()}`:null;
  useEffect(()=>{epoch.current++;setJob(null);setBusy(false);setHash(undefined);if(key){try{const saved=sessionStorage.getItem(key);if(saved){const parsed=JSON.parse(saved) as Request;if(/^0x[\da-f]{40}$/i.test(parsed.token)&&["holders","distribute"].includes(parsed.action)){setJob(parsed);setNotice("Checking saved transaction.");}}}catch{/* Optional storage. */}}},[key]);
  async function load(address=token){const version=++epoch.current;setHash(undefined);setLoading(true);setNotice("");try{const r=await fetch(`/api/claim?token=${encodeURIComponent(address)}`,{cache:"no-store"});const value=await r.json();if(!r.ok)throw Error(value.error);if(version===epoch.current){setData(value);setOffset(0);}}catch(e){if(version===epoch.current){setData(null);setNotice(e instanceof Error?e.message:"Could not load fees.");}}finally{if(version===epoch.current)setLoading(false);}}
  async function submit(request:Request,resume=false){
    if(running.current||!session?.csrfToken||!key)return;
    running.current=true;setBusy(true);const version=epoch.current;
    try{const r=await fetch("/api/claim",{method:"POST",headers:{"content-type":"application/json","x-argus-csrf":session.csrfToken},signal:AbortSignal.timeout(90000),body:JSON.stringify({...request,resume})});const result=await r.json();if(version!==epoch.current)return;if(!r.ok)throw Error(result.error);setNotice(result.message);setHash(result.hash);if(!result.pending&&!result.missing){setJob(null);try{sessionStorage.removeItem(key);}catch{/* Optional storage. */}if(result.status==="completed"){const fresh=await fetch(`/api/claim?token=${request.token}`,{cache:"no-store"});if(fresh.ok&&version===epoch.current)setData(await fresh.json());}}}
    catch(e){if(version===epoch.current)setNotice(e instanceof Error?e.message:"Request uncertain. Check your wallet history.");}
    finally{running.current=false;setBusy(false);}
  }
  useEffect(()=>{if(!job||!session?.authenticated)return;const timer=setInterval(()=>void submit(job,true),6000);return()=>clearInterval(timer);/* submit reads the current session */},[job,session]); // eslint-disable-line react-hooks/exhaustive-deps
  function start(action:Request["action"]){if(!data||!key||job||running.current)return;const request={token:data.token,requestId:crypto.randomUUID(),action,offset};try{sessionStorage.setItem(key,JSON.stringify(request));}catch{/* Server journal remains authoritative. */}setHash(undefined);setNotice("Processing. Preparing transaction.");setJob(request);void submit(request);}
  const disabled=!session?.authenticated||!!session.needsReauth||!!job||busy;
  const allocationTotal=data?Object.values(data.allocation).reduce((a,b)=>a+b,0):0;
  const share=(value:number)=>allocationTotal?`${(value*100/allocationTotal).toFixed(1)}% of token fees`:"";
  return <section className="claim-page"><h1>Claim</h1><p>Distribute token fees, run buybacks and burns, and send funded rewards to holders.</p>
    <form className="claim-lookup" onSubmit={e=>{e.preventDefault();void load();}}><label style={{flex:1}}>Token contract<input aria-label="Token contract address" placeholder="0x…" value={token} disabled={!!job} onChange={e=>setToken(e.target.value)} required pattern="0x[a-fA-F0-9]{40}"/></label><button disabled={loading||!!job}>{loading?"Loading…":"Load token"}</button></form>
    {notice&&<div className="claim-status" role="status"><button aria-label="Dismiss message" onClick={()=>setNotice("")}>×</button>{notice}{hash&&<p><a href={`https://www.arcexplorer.org/tx/${hash}`} target="_blank" rel="noreferrer">Transaction</a></p>}{job&&!busy&&<button onClick={()=>void submit(job,false)}>Retry same request</button>}</div>}
    {data&&<><h2>{data.symbol}</h2><p className="claim-contract">{data.token}</p><p>Each action uses your wallet’s Arc USDC for gas. Funds go to the recipients set by the token contract.</p>
      {!session?.authenticated||session.needsReauth?<WalletSignInButton destination="/claim">Sign in to Wallet</WalletSignInButton>:<p className="claim-wallet">You are using your {session.provider==="telegram"?"Telegram-linked":"X-linked"} wallet ({session.walletAddress?.slice(0,6)}…{session.walletAddress?.slice(-5)}).</p>}
      <div className="claim-grid">
        <article className="claim-card"><h3>In splitter</h3><strong>{amount(data.splitterQuote)} {data.quoteSymbol}</strong><strong>{amount(data.splitterTokens)} {data.symbol}</strong><p>Collected fees sit here until the contract allocates them to creator rewards, holders, burn, or liquidity.</p><small>Unallocated: {amount(data.unallocatedQuote)} {data.quoteSymbol} + {amount(data.unallocatedTokens)} {data.symbol}</small><button disabled={disabled||!data.canDistribute} onClick={()=>start("distribute")}>Distribute fees</button></article>
        {data.allocation.creator>0&&<article className="claim-card"><h3>Claimable creator fees</h3><small>{share(data.allocation.creator)}</small><strong>{amount(data.creatorQuote)} {data.quoteSymbol}</strong><strong>{amount(data.creatorTokens)} {data.symbol}</strong>{Number(data.creatorUsdc)>0&&<strong>{amount(data.creatorUsdc)} USDC</strong>}<p>These fees are credited to the token creator and can be claimed by that creator.</p><a href={`https://arguspad.io/token/${data.token}`} target="_blank" rel="noreferrer">Go to this page and click Claim Fees to claim available fees</a></article>}
        {data.allocation.holders>0&&<><article className="claim-card"><h3>Funded for holders</h3><small>{share(data.allocation.holders)}</small><strong>{amount(data.holderFunds)} {data.payoutSymbol}</strong><p>Rewards already in the holder contract pay each eligible holder according to their recorded entitlement.</p><small>Total paid: {amount(data.paid)} {data.payoutSymbol}</small><div className="claim-actions"><button disabled={disabled||!data.canPay} onClick={()=>start("holders")}>Send to holders</button><button disabled={!!job||busy} onClick={()=>setOffset(value=>value+100)}>Next holder page</button>{offset>0&&<button disabled={!!job} onClick={()=>setOffset(0)}>First page</button>}</div><small>Checks holders {offset+1}–{offset+100}; pays up to 50 eligible holders per transaction. Repeat for more payouts.</small></article><article className="claim-card"><h3>Held for future rewards</h3><strong>{amount(data.heldFunds)} {data.payoutSymbol}</strong><p>This portion of holder funding is held by the contract until its reward conditions are met.</p></article></>}
        {data.allocation.burn>0&&<article className="claim-card"><h3>Buyback and burn</h3><strong>{share(data.allocation.burn)}</strong><p>Distributing fees uses the contract’s burn allocation to buy and burn tokens within its current limits.</p><small>This allocation is part of the splitter balance, not an additional balance.</small><button disabled={disabled||!data.canDistribute} onClick={()=>start("distribute")}>Run distribution and burn</button></article>}
        {data.allocation.liquidity>0&&<article className="claim-card"><h3>Reserved for liquidity</h3><small>{share(data.allocation.liquidity)}</small><strong>{amount(data.principalQuote)} {data.quoteSymbol}</strong><strong>{amount(data.principalTokens)} {data.symbol}</strong><p>These funds are reserved by the contract for adding liquidity rather than holder or creator payouts.</p></article>}
      </div><small>Read from Arc block {data.block}. A confirmed call may process only part of the balance; contract limits still apply.</small><p><button disabled={loading||!!job} onClick={()=>void load(data.token)}>Refresh balances</button></p></>}
  </section>;
}
