"use client";
import { ArcTokenPicker } from "./ArcTokenPicker";
import { PersistentNotices, usePersistentNotices } from "./PersistentNotices";
import { ArcTradeControls } from "./ArcTradeControls";
import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { WalletControlsPreview } from "./WalletControlsPreview";
import { CopyWalletAddress } from "./CopyWalletAddress";
import { useOtcSession, units, webPost } from "./OtcClient";
type Data={baseUsdc?:{balance:string|null;locked:string;available:string|null};walletAddress:string;balances:Array<{chainId:number;listingReservedWei?:string;balanceWei:string|null;lockedWei:string;availableWei:string|null;pending:boolean;error?:string|null}>;
  orders:Array<{paymentAsset?:"ETH"|"USDC";approvalHash?:string;payoutAttempt?:number;id:string;amount:string;premiumBps:number;feeWei:string;totalWei:string;status:string;paymentHash?:string;payoutHash?:string;note?:string;side:string;createdAt:number}>;
  listings:Array<{id:string;available:string;held:string;premiumBps:number;status:string;sold:string;receivedEthWei:string;receivedUsdcUnits:string;returnedUsdc:string|null;settlementLocked:boolean;canCancel:boolean}>;
  transactions:Array<{id:string;chainId:number;leg:string;status:string;hash?:string;note?:string;createdAt:number}>};
type SendQuote={quote:string;amount:string;recipient:string;asset:string;gasWei:string;expiresAt:number};
export function WalletDashboard({address}:{address?:string}){
  const session=useOtcSession(),[data,setData]=useState<Data|null>(null),[tab,setTab]=useState<"buy"|"sell"|"swap"|"send"|"withdraw">("buy");
  const {notices,notify:setError,dismiss}=usePersistentNotices();
  const [busy,setBusy]=useState(false),[chain,setChain]=useState<5042|8453>(5042),[asset,setAsset]=useState("native"),[token,setToken]=useState(""),[amount,setAmount]=useState(""),[recipient,setRecipient]=useState(""),[quote,setQuote]=useState<SendQuote|null>(null),[now,setNow]=useState(Date.now());
  const balanceRequest=useRef<AbortController|null>(null);
  const sendInFlight=useRef(false);
  const owns=Boolean(session?.authenticated&&session.walletAddress&&(!address||session.walletAddress?.toLowerCase()===address.toLowerCase()));
  const refresh=useCallback(async()=>{
    if(!owns||balanceRequest.current)return;
    const controller=new AbortController();balanceRequest.current=controller;
    try{
      const response=await fetch("/api/otc?scope=wallet",{cache:"no-store",signal:AbortSignal.any([controller.signal,AbortSignal.timeout(45000)])});
      const result=await response.json();if(!response.ok)throw new Error(result.error||"Wallet data unavailable.");
      if(result.walletAddress?.toLowerCase()!==session?.walletAddress?.toLowerCase())throw new Error("Wallet account changed. Refresh the page.");
      if(!controller.signal.aborted){setData(result);for(const balance of (result as Data).balances){if(balance.error)setError(`${balance.chainId===5042?"Arc":"Base"}: ${balance.error}`);}}
    }catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Wallet data unavailable. Retry shortly.");}
    finally{if(balanceRequest.current===controller)balanceRequest.current=null;}
  },[owns,session?.walletAddress,setError]);
  useEffect(()=>{setData(null);void refresh();const interval=setInterval(()=>void refresh(),10_000);return()=>{clearInterval(interval);balanceRequest.current?.abort();balanceRequest.current=null;};},[refresh]);
  useEffect(()=>{const interval=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(interval);},[]);
  if(!session)return address?null:<WalletControlsPreview loading/>;
  if(!owns)return address?null:<WalletControlsPreview/>;
  return <div className="wallet-dashboard">
    {!address&&session.walletAddress&&<div className="wallet-connection-slot"><CopyWalletAddress address={session.walletAddress}/><a className="arc-button" href={`https://www.arcexplorer.org/address/${session.walletAddress}`} target="_blank" rel="noopener noreferrer">View on Arc Explorer ↗</a></div>}
    <div className="otc-wallet-balances">{[5042,...(data?.balances.some(b=>b.chainId===8453&&((b.balanceWei!=null&&BigInt(b.balanceWei)>0n)||BigInt(data?.baseUsdc?.balance??"0")>0n))?[8453]:[])].map(id=>{const b=data?.balances.find(item=>item.chainId===id);return <article key={id}><p className="arc-kicker">{id===5042?"ARC / USDC":"BASE / ETH"}</p><h2>{b?.availableWei==null?"—":units(b.availableWei,18)} <small>{id===5042?"USDC":"ETH"}</small></h2><span>Available</span><dl>{id===5042&&data?.listings.some(listing=>listing.status==="active"||listing.settlementLocked)&&<><dt>Reserved</dt><dd>{b?units(b.listingReservedWei??"0",18):"—"}</dd></>}<dt>Total balance</dt><dd>{b?.balanceWei==null?"—":units(b.balanceWei,18)}</dd></dl>{id===8453&&<dl><dt>Base USDC available</dt><dd>{data?.baseUsdc?.available==null?"—":units(data.baseUsdc.available)} USDC</dd><dt>Base USDC total</dt><dd>{data?.baseUsdc?.balance==null?"—":units(data.baseUsdc.balance)} USDC</dd></dl>}{b?.error&&<p className="otc-notice" role="status">{b.error} <button className="otc-inline-button" onClick={()=>void refresh()}>Retry</button></p>}{b?.pending&&<p className="otc-fine">Transaction pending.</p>}{id===8453&&<button className="arc-button" disabled={busy||b?.availableWei==null||BigInt(b.availableWei)<=0n} onClick={()=>{setTab("withdraw");setChain(8453);setAsset("native");setAmount("");setRecipient("");setQuote(null);}}>Withdraw</button>}</article>;})}</div>
    <div className="otc-panel-title"><h2>Move funds</h2><Link className="arc-text-link" href="/otc">Open OTC market ↗</Link></div>
    <div className="otc-tabs wallet-action-tabs" role="group" aria-label="Wallet action">{["buy","sell","swap","send"].map(action=><button key={action} aria-pressed={tab===action} onClick={()=>{setTab(action as typeof tab);setChain(5042);setAsset("native");setAmount("");setRecipient("");setQuote(null);}}>{action[0].toUpperCase()+action.slice(1)}</button>)}</div>
    {tab==="buy"||tab==="sell"||tab==="swap"?<ArcTradeControls key={tab} side={tab} onNotice={setError}/>:<section className="otc-form-panel"><h2>{tab==="withdraw"?"Withdraw Base ETH":"Send Arc tokens"}</h2><form onSubmit={async e=>{e.preventDefault();if(sendInFlight.current||busy||(asset==="token"&&!/^0x[0-9a-fA-F]{40}$/.test(token)))return;sendInFlight.current=true;setBusy(true);setQuote(null);try{const prepared=await webPost("/api/wallet/send",{action:"preview",chainId:chain,asset:asset==="token"?token:"native",amount,recipient},session);if(chain===8453){setQuote(prepared);}else{if(Date.now()>=prepared.expiresAt)throw new Error("Send quote expired. Try again.");const result=await webPost("/api/wallet/send",{action:"confirm",quote:prepared.quote},session);setError(`Send recorded: ${result.status}. See transaction history.`);await refresh();}}catch(e){setError(e instanceof Error?e.message:"Send failed. Check transaction history.");}finally{sendInFlight.current=false;setBusy(false);}}}>
      <p className="otc-fine">{chain===5042?"Arc network · USDC gas":"Base network · ETH gas"}</p>
      {chain===5042&&<label>Asset<select value={asset} onChange={e=>{setAsset(e.target.value);setQuote(null);}}><option value="native">USDC</option><option value="token">Arc token</option></select></label>}
      {asset==="token"&&<ArcTokenPicker label="Token" value={token} disabled={busy} onChange={address=>{setToken(address);setQuote(null);}}/>}
      <label>Amount<input required inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);setQuote(null);}}/></label><label>Recipient<input required value={recipient} onChange={e=>{setRecipient(e.target.value);setQuote(null);}} placeholder="0x…"/></label>
      <p className="otc-fine">Only unreserved funds can be sent. Gas is additional. </p><button className="arc-button" disabled={busy||(asset==="token"&&!/^0x[0-9a-fA-F]{40}$/.test(token))} type="submit">{busy?(tab==="withdraw"?"Preparing withdrawal…":"Preparing send…"):tab==="withdraw"?"Review withdrawal":"Send"}</button></form>
      {quote&&<div className="otc-quote"><h3>{tab==="withdraw"?"Confirm Base withdrawal":"Confirm send"}</h3><p>{quote.amount} {quote.asset}</p><p className="otc-address">To {quote.recipient}</p><p>Gas allowance: {units(quote.gasWei,18)} {chain===5042?"USDC":"ETH"}</p><button className="arc-button" disabled={busy||now>=quote.expiresAt} onClick={async()=>{setBusy(true);try{const result=await webPost("/api/wallet/send",{action:"confirm",quote:quote.quote},session);setQuote(null);await refresh();setError(`Send recorded: ${result.status}. See transaction history.`);}catch(e){setError(e instanceof Error?e.message:"Send failed.");}finally{setBusy(false);}}}>{now>=quote.expiresAt?"Quote expired":tab==="withdraw"?"Confirm withdrawal":"Confirm send"}</button></div>}
    </section>}
    <PersistentNotices notices={notices} dismiss={dismiss}/>
    <section className="otc-history"><div className="otc-panel-title"><h2>Your OTC positions</h2></div>{data?.listings.length?data.listings.map(l=><article className="otc-listing-row" key={l.id}><div><strong>{l.status==="active"?`${units(l.available)} USDC available`:l.status==="cancelled"?"Cancelled":"Closed"}</strong><p>{(l.premiumBps/100).toLocaleString()}% premium · {units(l.held)} USDC in orders · {l.status==="filled"?"closed":l.status}</p><p>{units(l.sold)} Arc USDC sold · Received {units(l.receivedEthWei,18)} Base ETH + {units(l.receivedUsdcUnits)} Base USDC</p>{l.returnedUsdc!==null&&<p>{units(l.returnedUsdc)} Arc USDC returned to available funds. Unused gas reserve unlocked.</p>}{l.settlementLocked&&<p>Settlement locked. Waiting for payment and delivery verification.</p>}</div>{l.status==="active"&&<button className="otc-inline-button" disabled={busy||!l.canCancel} onClick={async()=>{setBusy(true);try{await webPost("/api/otc",{action:"cancel",listingId:l.id},session);await refresh();}catch(e){setError(e instanceof Error?e.message:"Cancellation failed.");}finally{setBusy(false);}}}>Cancel listing</button>}</article>):<p className="otc-fine">{data?"No listings.":"Listing records unavailable."}</p>}</section>
    <section className="otc-history"><div className="otc-panel-title"><h2>OTC orders</h2><button className="otc-inline-button" onClick={()=>void refresh()}>Refresh ↻</button></div>{data?.orders.length?data.orders.sort((a,b)=>b.createdAt-a.createdAt).map(order=><article key={order.id} className="otc-order-row"><div><strong>{order.side.toUpperCase()} · {units(order.amount)} Arc USDC</strong><span className="otc-status">{order.status.replaceAll("_"," ")}</span></div><p>{new Date(order.createdAt).toLocaleString()} · Premium {(order.premiumBps/100).toLocaleString()}% · Payment {units(order.totalWei,order.paymentAsset==="USDC"?6:18)} Base {order.paymentAsset??"ETH"} · Fee {units(order.feeWei,order.paymentAsset==="USDC"?6:18)} {order.paymentAsset??"ETH"}</p>{order.note&&<p>{order.note}</p>}{order.side==="sell"&&order.status==="payout_failed"&&<button className="arc-button" disabled={busy} onClick={async()=>{setBusy(true);try{await webPost("/api/otc",{action:"retry_payout",orderId:order.id,attempt:order.payoutAttempt??0},session);await refresh();}catch(e){setError(e instanceof Error?e.message:"Payout retry failed.");}finally{setBusy(false);}}}>Retry Arc payout</button>}<div className="otc-transaction-links">{order.approvalHash&&<a href={`https://basescan.org/tx/${order.approvalHash}`} target="_blank" rel="noreferrer">USDC approval ↗</a>}{order.paymentHash&&<a href={`https://basescan.org/tx/${order.paymentHash}`} target="_blank" rel="noreferrer">Base payment ↗</a>}{order.payoutHash&&<a href={`https://www.arcexplorer.org/tx/${order.payoutHash}`} target="_blank" rel="noreferrer">Arc payout ↗</a>}</div><small>{order.id}</small></article>):<p className="otc-fine">{data?"No OTC orders.":"Order records unavailable."}</p>}</section>
    <section className="otc-history"><h2>Transactions</h2>{data?.transactions.length?[...data.transactions].sort((a,b)=>b.createdAt-a.createdAt).map(tx=><article key={tx.id} className="otc-listing-row"><div><strong>{tx.chainId===5042?"Arc":"Base"} · {tx.leg}</strong><p>{tx.status.replaceAll("_"," ")} · {new Date(tx.createdAt).toLocaleString()}</p>{tx.note&&<p>{tx.note}</p>}</div>{tx.hash&&<a className="arc-text-link" href={`${tx.chainId===5042?"https://www.arcexplorer.org":"https://basescan.org"}/tx/${tx.hash}`} target="_blank" rel="noreferrer">View ↗</a>}</article>):<p className="otc-fine">{data?"No transactions.":"Transaction records unavailable."}</p>}</section>
  </div>;
}
