import {randomBytes} from "node:crypto";
import {exportBrowserLinks} from "@/lib/key-export/browser-return";
import {brokerConfiguration} from "@/lib/key-export/broker";
export const runtime="nodejs";
export const dynamic="force-dynamic";
export async function GET(request:Request){
  try{
    const config=brokerConfiguration(request);const nonce=randomBytes(24).toString("base64");
    const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Export wallet key · Argos Bot</title><style nonce="${nonce}">:root{color-scheme:dark}body{margin:0;background:#061827;color:#edf6ff;font:16px system-ui}main{max-width:620px;margin:8vh auto;padding:24px}h1{font-size:28px}p{line-height:1.6}#details{overflow-wrap:anywhere;font-size:14px}button{background:#c5e6ff;color:#051725;padding:12px 18px;border:0;border-radius:8px;margin:8px 8px 8px 0;font:inherit;cursor:pointer}button:disabled{opacity:.45;cursor:default}#key{box-sizing:border-box;width:100%;font:14px monospace;padding:14px;background:#122e45;color:white;border:1px solid #6893b1;word-break:break-all}#message{min-height:3em}a{color:#b6e2ff}[hidden]{display:none!important}label{display:block;margin:20px 0}</style></head><body><main><h1>Export your private key</h1><p id="details"></p><p>Your private key controls this wallet on every EVM chain. Anyone with it can access every asset in this wallet. Never share your private key. Exporting does not disconnect Argos Bot or revoke approvals.</p><p id="message" role="status" aria-live="polite">Checking export request…</p><button id="verify" hidden>Verify ownership</button><div id="consent" hidden><label><input type="checkbox" id="confirm"> I understand this key gives full control of this wallet and must stay private.</label></div><button id="reveal" hidden disabled>Reveal private key</button><button id="retry" hidden>Retry encrypted export</button><input id="key" aria-label="Private key" readonly hidden autocomplete="off" spellcheck="false"><button id="copy" hidden>Copy private key</button><button id="close">Hide and close export</button>${exportBrowserLinks(config.origin,request.headers.get("user-agent")??"")}<noscript>JavaScript is required. No key will be sent in chat.</noscript></main><script nonce="${nonce}" src="/api/key-export/script"></script></body></html>`;
    return new Response(html,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","referrer-policy":"no-referrer","x-content-type-options":"nosniff","content-security-policy":`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; base-uri 'none'; object-src 'none'; form-action 'none'; frame-ancestors https://web.telegram.org https://webk.telegram.org https://webz.telegram.org`,"permissions-policy":"camera=(), microphone=(), geolocation=(), payment=()"}});
  }catch{return new Response("Key export is unavailable.",{status:404,headers:{"content-type":"text/plain","cache-control":"no-store"}});}
}
