import { pageMetadata } from "@/lib/site-metadata";
import type { Metadata } from "next";
import { LegalDocument, type LegalSection } from "@/components/LegalDocument";

export const metadata: Metadata = pageMetadata("/terms", "Terms that apply when accessing or using Arctos Bot.");

const sections: LegalSection[] = [
  { title: "Agreement", paragraphs: ["These Terms of Use govern your access to the Arctos Bot website and Arctos Bot features offered through the website, X, wallets, and related services. By using Arctos Bot, you agree to these Terms and the Privacy Policy. If you do not agree, do not use the service."] },
  { title: "About Arctos Bot", paragraphs: ["Arctos Bot provides software for creating and viewing wallets and for requesting interactions with tokens, public blockchains, smart contracts, and third-party services. Arctos Bot is independent and is not operated or endorsed by Arc, X, or Coinbase.", "Arctos Bot contact details will be published before release."] },
  { title: "Eligibility", paragraphs: ["You must be at least 18 years old, have legal capacity to agree to these Terms, and be permitted to use Arctos Bot under the laws that apply to you. You may not use the service where its use would be unlawful, including in violation of sanctions or export restrictions."] },
  { title: "Wallets and account security", paragraphs: ["An Arctos Bot wallet may be associated with your authenticated X account. You are responsible for protecting your X account, devices, sessions, and any credentials connected with your use of Arctos Bot. Instructions authenticated as coming from your account may be treated as authorized by you."] },
  { title: "Transactions and authorization", paragraphs: ["You are responsible for reviewing every instruction, amount, asset, address, network, pool, range, fee setting, and other transaction detail before submitting it. A request to Arctos Bot authorizes the service and its providers to prepare and, where the workflow permits, submit the corresponding blockchain or third-party action from your Arctos Bot wallet.", "Blockchain transactions may be irreversible. Arctos Bot cannot guarantee that a transaction will be accepted, execute at an expected price, complete by an estimated time, or be reversible after submission."] },
  { title: "Tokens and content", paragraphs: ["Tokens and token content are provided by users. Arctos Bot does not endorse a token, creator, claim, image, link, or project merely because it appears on the service. Names and tickers may be duplicated, so you should verify the contract address.", "You must have the rights needed for content you submit and must not provide unlawful, deceptive, infringing, malicious, or abusive content. Arctos Bot may restrict or remove content from surfaces it controls."] },
  { title: "Trading and swaps", paragraphs: ["Trading, swaps, fee claims, and burns involve independent networks, protocols, contracts, pools, and providers. Their rules, fees, availability, and risks also apply."] },
  { title: "Acceptable use", bullets: ["Do not use Arctos Bot for unlawful activity, fraud, market manipulation, sanctions evasion, theft, harassment, spam, or infringement.", "Do not attempt to access another user's wallet, impersonate another person, bypass safeguards or limits, interfere with the service, or exploit errors.", "Do not submit malicious code, deceptive links, or content that violates another person's rights.", "Do not use automated traffic in a way that degrades Arctos Bot or third-party services."] },
  { title: "No warranties", paragraphs: ["Arctos Bot is provided on an as-is and as-available basis to the fullest extent permitted by law. We disclaim warranties of merchantability, fitness for a particular purpose, title, non-infringement, accuracy, uninterrupted operation, security, and successful transaction execution."] },
  { title: "Limitation of liability", paragraphs: ["To the fullest extent permitted by law, Arctos Bot and its operators will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost assets, profits, data, opportunities, goodwill, or access arising from use of or inability to use the service, blockchain activity, tokens, smart contracts, third-party services, account compromise, or inaccurate information.", "Nothing in these Terms excludes liability that cannot lawfully be excluded or limited."] },
  { title: "Your responsibility", paragraphs: ["You are solely responsible for deciding whether and how to use Arctos Bot and for the consequences of your instructions. To the extent permitted by law, you agree to defend and indemnify Arctos Bot and its operators from claims arising from your unlawful use, submitted content, violation of these Terms, or infringement of another person's rights."] },
  { title: "Changes and contact", paragraphs: ["We may update these Terms as the service changes. Continued use after an updated version becomes effective constitutes acceptance of the revised Terms.", "For questions about these Terms, contact Arctos Bot support."] },
];

export default function TermsPage() { return <LegalDocument eyebrow="Arctos Bot legal" title="Terms of Use" summary="The conditions, responsibilities, and risks that apply when you use Arctos Bot." sections={sections} />; }
